language: rust
dist: xenial

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gpu
      rust: nightly
    - env: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - source ~/.cargo/env

script:
  - cargo build
  - cargo test

after_script:
  set +e

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
    email:
        on_success: never
