language: rust
dist: xenial

addons:
  apt:
    packages:
      - libssl-dev

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly-2019-03-20
    - env: osx
      rust: nightly-2019-03-20

before_install:
  - set -e
  - rustup self update

install:
  - source ~/.cargo/env

script:
  - cargo clean
  - cargo build
  - cargo test

after_script:
  set +e

cache: cargo
before_cache: |
  chmod -R a+r $HOME/.cargo
  if [[ "$TRAVIS_OS_NAME" == linux ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi


after_success:
  if [[ "$TRAVIS_OS_NAME" == linux ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
    email:
        on_success: never
