trigger: ["master"]
pr: ["master"]

variables:
  nightly: nightly-2019-06-02

jobs:
# Check formatting
- template: ci/azure-rustfmt.yml
  parameters:
    name: rustfmt

# Run async-await tests
- template: ci/azure-test.yml
  parameters:
    name: test
    displayName: Test Async / Await
    rust: $(nightly)
