[package]
name = "grass"
version = "0.1.0"
authors = ["elbaro <elbaro@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
strfmt = "0.1.6"
env_logger = "0.6.1"
log = "0.4.6"
slog = "2.4.1"
slog-term = "2.4.0"
slog-async = "2.3.0"
pidlock = "0.1.2"
# futures = "0.1"
curl = "0.4.19"
uuid = {version="0.7.3", features=["v4"]}
serde_json = "1.0.39"
json5 = "0.2.4"
crossbeam = "0.7.1"
clone_all = "0.1.1"
serde = { version = "1.0.89", features = ["derive"] }
prettytable-rs = "0.8.0"
term = "0.5.1"
rust_decimal = "0.11.2"
num = "0.2.0"
textwrap = "0.11.0"
preferences = "1.1.0"
self_update = "0.5.1"
app_dirs = "1.2.1"
toml = "0.5.0"
once_cell = "0.1.8"
# essrpc = {version="0.2.0", path="essrpc/essrpc", features=["bincode_transport"]}
chrono = {version="0.4.6", features=["serde"]}
stream-cancel = "0.4.4"
tokio = {version="0.1.18", features=["async-await-preview"]}
futures-preview = {version="0.3.0-alpha.13", features=["compat", "io-compat"]}
