[package]
name = "grass"
version = "0.1.0"
authors = ["elbaro <elbaro@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
strfmt = "0.1.6"
env_logger = "0.6.1"
log = "0.4.6"
slog = "2.4.1"
slog-term = "2.4.0"
slog-async = "2.3.0"
pidlock = "0.1.2"
actix-web = "0.7.18"
tokio-uds = "0.2.5"
actix = "0.7.9"
decimal = "2.0.4"
futures = "0.1"
curl = "0.4.19"
uuid = {version="0.7.2", features=["v4"]}
serde_json = "1.0.39"
json5 = "0.2.4"
crossbeam = "0.7.1"
clone_all = "0.1.1"
serde = { version = "1.0.89", features = ["derive"] }
