jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.14
      Windows:
        vmImage: windows-2019
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - template: azure-patch-crates.yml

  - script: cargo check --all
    displayName: cargo +nightly check --all

  # Check benches
  - script: cargo check --benches --all
    displayName: Check benchmarks
