jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
        binary: ubuntu-16_04
      MacOS:
        vmImage: macOS-10.14
        binary: mac-mojave
      Windows:
        vmImage: windows-2019
        binary: windows
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - template: azure-patch-crates.yml

  - script: cargo test --all
    displayName: cargo test --all

  # Check benches
  - script: cargo check --benches --all
    displayName: Check benchmarks

  - script: cargo build --release
    displayName: cargo build --release

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'grass_$(binary)'
      targetPath: 'target/release/grass'
